CREATE TABLE IF NOT EXISTS `ublack_reservation` (
  `ID` int(18) NOT NULL AUTO_INCREMENT,
  `ID_PRICE` int(18) NOT NULL,
  `DATE` DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PRICE` int(18) NOT NULL,
  PRIMARY KEY (`ID`)
);